services:
  
  certs:
    container_name: oe-certs 
    image: itechuw/certgen:main
    restart: always
    environment:
      - KEYSTORE_PW="kspass"
      - TRUSTSTORE_PW="tspass"
    networks:
      - hie
    volumes:
      -  key_trust-store-volume:/etc/openelis-global
      -  keys-vol:/etc/ssl/private/
      -  certs-vol:/etc/ssl/certs/

  database:
    container_name: openelisglobal-database 
    image: postgres:14.4
    ports:
        - "15432:5432"
    restart: always
    env_file:
        - ./configs/openelis/database/database.env
    volumes:
          # preserves the database between containers
          - db-data2:/var/lib/postgresql/data                
          # files here will run on install
          - ./configs/openelis/database/dbInit:/docker-entrypoint-initdb.d
    networks:
        - hie
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "clinlims", "-U", "clinlims" ]
        timeout: 45s
        interval: 10s
        retries: 10 
            
  oe.openelis.org:
    container_name: openelisglobal-webapp 
    image: itechuw/openelis-global-2-dev:oebackend
    depends_on:
        - database
        - certs
    ports:
        - "8080:8080"
        - "8443:8443"
    restart: always
    networks:
      hie:
        ipv4_address: 172.20.1.121
  
    environment:
        - DEFAULT_PW=adminADMIN! 
        - TZ=Africa/Nairobi
          # context.xml doesn't seem to be able to pick up environment variables directly, so we are passing them in as CATALINA_OPTS
        - CATALINA_OPTS= -Ddatasource.url=jdbc:postgresql://database:5432/clinlims -Ddatasource.username=clinlims -Ddatasource.password=clinlims
    volumes:
        -  key_trust-store-volume:/etc/openelis-global
        - ./volume/plugins/:/var/lib/openelis-global/plugins
        - ./configs/openelis/tomcat/oe_server.xml:/usr/local/tomcat/conf/server.xml
        -  lucene_index-vol:/var/lib/lucene_index
    secrets:
        - source: datasource.password
        - source: common.properties
            
  fhir.openelis.org:
    container_name: external-fhir-api
    image: hapiproject/hapi:v6.6.0-tomcat
    depends_on:
        - database
        - certs
    ports:
        - "8081:8080"
        - "8444:8443"
    networks:
        - hie
    restart: always
    environment:
      SPRING_CONFIG_LOCATION: file:///run/secrets/hapi_application.yaml
      TZ: Africa/Nairobi
      JAVA_OPTS: "-Djavax.net.ssl.trustStore=/etc/openelis-global/truststore 
                  -Djavax.net.ssl.trustStorePassword=tspass
                  -Djavax.net.ssl.trustStoreType=pkcs12 
                  -Djavax.net.ssl.keyStore=/etc/openelis-global/keystore 
                  -Djavax.net.ssl.keyStorePassword=kspass 
                  -Djavax.net.ssl.keyStoreType=pkcs12"            
    
    volumes:
        -  key_trust-store-volume:/etc/openelis-global
        - ./configs/openelis/tomcat/hapi_server.xml:/opt/bitnami/tomcat/conf/server.xml
    secrets:
          - source: hapi_application.yaml 

  frontend.openelis.org:
    image: itechuw/openelis-global-2-frontend-dev:oefrontend
    container_name: openelisglobal-front-end
    networks:
        - hie

  proxy:
    image: nginx:1.15-alpine
    container_name: openelisglobal-proxy
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - certs-vol:/etc/nginx/certs/
        - keys-vol:/etc/nginx/keys/
        - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
        - hie
    restart: unless-stopped
    depends_on:
      - certs 

  odoo:
    image: odoo:16.0
    container_name: openelis-odoo
    depends_on:
        - odoo-db
    ports:
        - "8069:8069"
    volumes:
        - odoo-web-data:/var/lib/odoo
        - ./configs/odoo/config:/etc/odoo
        - ./configs/odoo/addons:/mnt/extra-addons
    environment:
        - HOST=odoo-db
        - USER=odoo
        - PASSWORD=odoo
    networks:
        - hie

  odoo-db:
    image: postgres:13
    container_name: odoo-database
    environment:
        - POSTGRES_DB=postgres
        - POSTGRES_PASSWORD=odoo
        - POSTGRES_USER=odoo
    volumes:
        - odoo-db-data:/var/lib/postgresql/data
    networks:
        - hie
            
secrets:
  datasource.password:
    file: ./configs/openelis/properties/datasource.password
  common.properties:
    file: ./configs/openelis/properties/common.properties
  hapi_application.yaml:
    file: ./configs/openelis/properties/hapi_application.yaml    

networks:
  hie:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.1.0/24
        
volumes:
  db-data2:
  key_trust-store-volume:
  certs-vol:
  certs:
  keys-vol:
  lucene_index-vol:
  odoo-web-data:
  odoo-db-data:
